version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379

  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DOCKERIZED: True
    ports:
      - 8081:8081
    depends_on:
      - redis
