swagger: "2.0"
info:
  title: Brand API
  version: 1.0.0
host: localhost
basePath: /
schemes:
  - https
produces:
  - application/json
paths:
  /v1/brand:
    get:
      tags:
        - Brand
      summary: Get a list of brands
      parameters:
        - name: skip
          in: query
          required: false
          type: integer
          default: 0
          format: int32
        - name: take
          in: query
          required: false
          type: integer
          default: 20
          format: int32
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/BrandResponse"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/ErrorResponse"
        "401":
          description: Unauthorized
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
        - TokenAuth: []
    post:
      tags:
        - Brand
      summary: Create a brand
      responses:
        "201":
          description: Created
          schema:
            $ref: "#/definitions/BrandResponse"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/ErrorResponse"
        "401":
          description: Unauthorized
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
        - TokenAuth: []
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          description: Brand object
          required: true
          schema:
            $ref: "#/definitions/BrandCreateRequest"
definitions:
  BrandCreateRequest:
    type: "object"
    properties:
      name:
        type: "string"
  BrandResponse:
    type: "object"
    properties:
      added:
        type: "integer"
        format: "int32"
      addedby:
        type: "string"
      changed:
        type: "integer"
        format: "int32"
      changedby:
        type: "string"
      id:
        type: "integer"
        format: "int32"
      name:
        type: "string"
    example:
      added: 0
      addedby: "addedby"
      changedby: "changedby"
      name: "name"
      id: 1
      changed: 6
  ErrorResponse:
    type: "object"
    properties:
      message:
        type: "string"
securityDefinitions:
  TokenAuth:
    type: "apiKey"
    name: "Authorization"
    in: "header"
